global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

accesslog:
  format: json

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          permanent: true
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

certificatesResolvers:
  myresolver:
    acme:
      email: demo@somewhere.com
      storage: /data/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web


providers:
  file:
    directory: "/etc/traefik.d/"
    watch: true
