http:
  middlewares:
    middle-cors:
      headers:
        accessControlAllowOriginList: 
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "HEAD"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
          - "PATCH"
        accessControlAllowHeaders:
          - DNT
          - X-CustomHeader
          - Keep-Alive
          - User-Agent
          - X-Requested-With
          - If-Modified-Since
          - Cache-Control
          - Content-Type
          - Authorization
